# Generated by Django 5.1.1 on 2024-09-13 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texturemodel',
            name='slug',
        ),
    ]
